# Generated by Django 5.0.6 on 2024-07-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0007_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('testimonial', models.TextField()),
                ('rating', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to='testimonials/')),
            ],
        ),
    ]
