# Generated by Django 5.0.6 on 2024-07-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0009_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.IntegerField(choices=[(1, 'Breakfast'), (2, 'Lunch'), (3, 'Dinner')], verbose_name='Category')),
                ('type', models.IntegerField(choices=[(1, 'Veg'), (2, 'Non-Veg')], verbose_name='Type')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_items')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('is_vegetarian', models.BooleanField(default=False, verbose_name='Is Vegetarian')),
            ],
        ),
    ]
