# Generated by Django 5.0.6 on 2024-07-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0010_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.IntegerField(choices=[('Breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('Dinner', 'Dinner')], verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='type',
            field=models.IntegerField(choices=[('veg', 'Veg'), ('nonveg', 'Non-Veg')], verbose_name='Type'),
        ),
    ]
