# Generated by Django 5.0.6 on 2024-07-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0014_alter_menuitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='type',
            field=models.CharField(blank=True, choices=[(1, 'Veg'), (2, 'Non-Veg'), (3, 'Drinks')], max_length=10, null=True, verbose_name='Type'),
        ),
    ]
