# Generated by Django 5.0.6 on 2024-07-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0016_alter_menuitem_category_alter_menuitem_type_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
