# Generated by Django 5.0.6 on 2024-07-17 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0024_alter_menuitem_category_alter_menuitem_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.IntegerField(choices=[(1, 'Breakfast'), (2, 'Lunch'), (3, 'Dinner')], verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='type',
            field=models.IntegerField(choices=[(1, 'Veg'), (2, 'Non-Veg'), (3, 'HotDrinks'), (4, 'ColdDrinks')], default='', verbose_name='type'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('qty', models.IntegerField(default=1)),
                ('amt', models.FloatField(default=0.0)),
                ('is_Paid', models.BooleanField(default=False)),
                ('is_ready', models.BooleanField(default=False)),
                ('update_desc', models.CharField(max_length=5000)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('m_id', models.ForeignKey(db_column='m_id', on_delete=django.db.models.deletion.CASCADE, to='foodapp.menuitem')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=50)),
                ('rozar_pay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('rozar_pay_Payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_Paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapp.order')),
            ],
        ),
    ]
