# Generated by Django 5.0.6 on 2024-07-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0026_rename_rozar_pay_payment_id_payment_rozarpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
